import { CalendarClock, CreditCard, Landmark, RefreshCw, TrendingDown, TrendingUp } from "lucide-react";
import type { FinanceData, RecurringPreference } from "../types";
import { recurringInsights } from "../lib/health";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const date = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR");

export function RecurringPage({ data, onUpdate }: { data: FinanceData; onUpdate: (input: Omit<RecurringPreference, "id">) => Promise<void> }) {
  const items = recurringInsights(data).filter((item) => data.recurringPreferences?.find((preference) => preference.fingerprint === item.key)?.status !== "ignored");
  const income = items.filter((item) => item.kind === "income");
  const expenses = items.filter((item) => item.kind === "expense");
  const monthlyIncome = income.reduce((sum, item) => sum + item.average, 0);
  const monthlyExpenses = expenses.reduce((sum, item) => sum + item.average, 0);
  return <div className="page-stack"><section className="page-title"><div><span className="eyebrow">Padrões detectados</span><h1>Gastos recorrentes</h1><p>Assinaturas, contas e rendas que se repetem com regularidade. Use esta visão para antecipar compromissos e revisar excessos.</p></div><span className="source-tag"><RefreshCw size={13} /> análise local</span></section>
    <section className="metrics-grid"><article className="metric-card emerald"><div className="metric-top"><span>Renda recorrente</span><span className="metric-icon"><TrendingUp size={18} /></span></div><strong>{brl.format(monthlyIncome)}</strong><small>{income.length} padrão{income.length === 1 ? "" : "ões"} identificado{income.length === 1 ? "" : "s"}</small></article><article className="metric-card"><div className="metric-top"><span>Compromissos recorrentes</span><span className="metric-icon"><TrendingDown size={18} /></span></div><strong>{brl.format(monthlyExpenses)}</strong><small>{expenses.length} cobrança{expenses.length === 1 ? "" : "s"} mensal{expenses.length === 1 ? "" : "is"}</small></article><article className="metric-card navy"><div className="metric-top"><span>Saldo comprometido</span><span className="metric-icon"><CalendarClock size={18} /></span></div><strong>{brl.format(monthlyIncome - monthlyExpenses)}</strong><small>renda recorrente menos custos previstos</small></article></section>
    <section className="panel recurring-panel"><div className="panel-heading"><div><span className="eyebrow">Detalhamento</span><h2>Movimentos mensais</h2></div><small>mínimo de 3 ocorrências • variação máxima de 10%</small></div>{items.length ? <div className="recurring-list">{items.map((item) => { const preference = data.recurringPreferences?.find((entry) => entry.fingerprint === item.key); return <div className="recurring-row" key={item.key}><span className={`round-icon ${item.kind === "income" ? "green" : "soft"}`}>{item.kind === "income" ? <TrendingUp size={18} /> : item.cardId ? <CreditCard size={18} /> : <Landmark size={18} />}</span><div className="recurring-main"><strong>{preference?.alias || item.name}{preference?.status === "confirmed" && <span className="source-tag">Confirmado</span>}</strong><small>{item.kind === "income" ? "Receita" : "Despesa"} • última ocorrência {date(item.lastOccurrence)} • próxima estimada {date(item.nextExpectedDate)}</small><div className="progress"><span style={{ width: `${Math.round(item.regularityScore * 100)}%` }} /></div><small>{Math.round(item.regularityScore * 100)}% de regularidade • intervalo médio de {item.intervalDays} dias • {item.occurrences} ocorrências</small><div className="recurring-actions"><button onClick={() => void onUpdate({ fingerprint: item.key, status: "confirmed", kind: item.kind, expectedAmount: item.average, alias: preference?.alias })}>Confirmar</button><button onClick={() => void onUpdate({ fingerprint: item.key, status: "cancelled", kind: item.kind, expectedAmount: item.average, alias: preference?.alias })}>Cancelada</button><button onClick={() => void onUpdate({ fingerprint: item.key, status: "ignored", kind: item.kind, expectedAmount: item.average })}>Ignorar</button></div></div><div className="recurring-values"><strong className={item.kind === "income" ? "positive" : ""}>{item.kind === "income" ? "+" : "−"} {brl.format(item.average)}</strong><small>{brl.format(item.annual)} / ano</small></div></div>; })}</div> : <div className="empty-state"><RefreshCw size={25} /><strong>Ainda não há padrões suficientes</strong><span>Após três ocorrências mensais semelhantes, elas aparecerão aqui automaticamente.</span></div>}</section>
    <article className="panel recurring-note"><strong>Como a análise funciona</strong><span>Descrições são normalizadas, compras parceladas e transferências ficam fora e somente movimentos mensais com intervalos consistentes entram no resultado. Isso evita transformar um gasto isolado em assinatura.</span></article>
  </div>;
}
